name: 'Sync (at night)'

on:
  schedule:
    - cron: '0 2 * * *'  # ogni giorno alle 02:00 UTC

  workflow_dispatch:  # esecuzione manuale
    inputs:
      sync_test_mode:
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    # Step 1: checkout del repository
    - name: Checkout target repo
      uses: taiki-e/checkout-action@v1.4.1

    # Step 2: sincronizzazione con upstream
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.2
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: realbestia1/EasyProxy
        test_mode: ${{ inputs.sync_test_mode }}

    # Step 3: messaggi di output
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."

    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."

    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
